app:
    resource: "@InitBundle/Controller/"
    type:     annotation
    prefix:   /

AppRestBundle:
    resource: "@RestBundle/Resources/config/routing.yml"

AppContatoBundle:
    resource: "@ContatoBundle/Resources/config/routing.yml"